spring:
  kafka:
    producer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}
    admin:
      properties:
        bootstrap.servers: ${spring.embedded.kafka.brokers}

logging:
  level:
    com:
      library_with_kafka:
        event_producer: DEBUG