spring:
  kafka:
    producer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: ${spring.embedded.kafka.brokers}

logging:
  level:
    com:
      library_with_kafka:
        event_consumer: DEBUG