server:
  port: 8081

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    admin:
      properties:
        bootstrap.servers: localhost:9092

logging:
  level:
    com:
      library_with_kafka:
        event_producer: DEBUG

retryListener:
  library:
    active: true