server:
  port: 8081

spring:
  application:
    name: LibraryEventProducer

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092

logging:
  level:
    com:
      library_with_kafka:
        event_producer: DEBUG